name: repository dispatch reception
on:
  repository_dispatch:
    types: [build_dispatch]
jobs:
  build_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: |
          echo ${{ github.event.client_payload.message }}
          echo ${{ github.event.client_payload.build }}
